# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.13

# Mod Properties
mod_name=Excessive Building
mod_version=4.0.0
maven_group=net.yirmiri.excessive_building
archives_base_name=[1.20.1] Excessive Building-fabric

# Dependencies
fabric_version=0.92.5+1.20.1
forge_config_api_version=8.0.0