# Project
version=4.0.0
group=net.yirmiri.excessive_building
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Excessive Building
mod_author=Yirmiri
mod_id=excessive_building
license=AZURUNE License
credits=
description=Excessive Building is a mod designed to enhance the building experience while maintaining Minecraft's style.
minecraft_version_range=[1.21.1, 1.22)

# Mappings
parchment_minecraft=1.21
parchment_version=2024.11.10
neo_form_version=1.21.1-20240808.144430

# Runic
neoforge_runiclib=7662213
fabric_runiclib=7662211

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)
