package net.yirmiri.excessive_building.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.util.DyeColor;
import net.yirmiri.excessive_building.registry.EBBlocks;
import net.yirmiri.excessive_building.registry.EBItems;
import org.apache.commons.lang3.StringUtils;

import java.util.concurrent.CompletableFuture;

public class EBEnUsLangGen extends FabricLanguageProvider {
    public EBEnUsLangGen(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generateTranslations(RegistryWrapper.WrapperLookup lookup, TranslationBuilder build) {
        for (DyeColor colors : DyeColor.values()) {
            String dyeString = StringUtils.capitalize(StringUtils.replace(StringUtils.replace(StringUtils.replace(colors.getName(),
                    "_", " "), "gray", "Gray"), "blue", "Blue"));

            build.add(EBBlocks.getDyedKnittedWools(colors.getId()), dyeString + " Knitted Wool");
            build.add(EBBlocks.getDyedKnittedCarpets(colors.getId()), dyeString + " Knitted Carpet");

            build.add(EBBlocks.getDyedTerracottaTiles(colors.getId()), dyeString + " Terracotta Tiles");
            build.add(EBBlocks.getDyedTerracottaTileStairs(colors.getId()), dyeString + " Terracotta Tile Stairs");
            build.add(EBBlocks.getDyedTerracottaTileVerticalStairs(colors.getId()), dyeString + " Terracotta Tile Vertical Stairs");
            build.add(EBBlocks.getDyedTerracottaTileSlab(colors.getId()), dyeString + " Terracotta Tile Slab");
        }

        //BLOCKS
        build.add(EBBlocks.OAK_MOSAIC, "Oak Mosaic");
        build.add(EBBlocks.OAK_MOSAIC_STAIRS, "Oak Mosaic Stairs");
        build.add(EBBlocks.OAK_MOSAIC_SLAB, "Oak Mosaic Slab");
        build.add(EBBlocks.OAK_MOSAIC_VERTICAL_STAIRS, "Oak Mosaic Vertical Stairs");
        build.add(EBBlocks.SPRUCE_MOSAIC, "Spruce Mosaic");
        build.add(EBBlocks.SPRUCE_MOSAIC_STAIRS, "Spruce Mosaic Stairs");
        build.add(EBBlocks.SPRUCE_MOSAIC_SLAB, "Spruce Mosaic Slab");
        build.add(EBBlocks.SPRUCE_MOSAIC_VERTICAL_STAIRS, "Spruce Mosaic Vertical Stairs");
        build.add(EBBlocks.BIRCH_MOSAIC, "Birch Mosaic");
        build.add(EBBlocks.BIRCH_MOSAIC_STAIRS, "Birch Mosaic Stairs");
        build.add(EBBlocks.BIRCH_MOSAIC_SLAB, "Birch Mosaic Slab");
        build.add(EBBlocks.BIRCH_MOSAIC_VERTICAL_STAIRS, "Birch Mosaic Vertical Stairs");
        build.add(EBBlocks.JUNGLE_MOSAIC, "Jungle Mosaic");
        build.add(EBBlocks.JUNGLE_MOSAIC_STAIRS, "Jungle Mosaic Stairs");
        build.add(EBBlocks.JUNGLE_MOSAIC_SLAB, "Jungle Mosaic Slab");
        build.add(EBBlocks.JUNGLE_MOSAIC_VERTICAL_STAIRS, "Jungle Mosaic Vertical Stairs");
        build.add(EBBlocks.ACACIA_MOSAIC, "Acacia Mosaic");
        build.add(EBBlocks.ACACIA_MOSAIC_STAIRS, "Acacia Mosaic Stairs");
        build.add(EBBlocks.ACACIA_MOSAIC_SLAB, "Acacia Mosaic Slab");
        build.add(EBBlocks.ACACIA_MOSAIC_VERTICAL_STAIRS, "Acacia Mosaic Vertical Stairs");
        build.add(EBBlocks.DARK_OAK_MOSAIC, "Dark Oak Mosaic");
        build.add(EBBlocks.DARK_OAK_MOSAIC_STAIRS, "Dark Oak Mosaic Stairs");
        build.add(EBBlocks.DARK_OAK_MOSAIC_SLAB, "Dark Oak Mosaic Slab");
        build.add(EBBlocks.DARK_OAK_MOSAIC_VERTICAL_STAIRS, "Dark Oak Mosaic Vertical Stairs");
        build.add(EBBlocks.MANGROVE_MOSAIC, "Mangrove Mosaic");
        build.add(EBBlocks.MANGROVE_MOSAIC_STAIRS, "Mangrove Mosaic Stairs");
        build.add(EBBlocks.MANGROVE_MOSAIC_SLAB, "Mangrove Mosaic Slab");
        build.add(EBBlocks.MANGROVE_MOSAIC_VERTICAL_STAIRS, "Mangrove Mosaic Vertical Stairs");
        build.add(EBBlocks.CHERRY_MOSAIC, "Cherry Mosaic");
        build.add(EBBlocks.CHERRY_MOSAIC_STAIRS, "Cherry Mosaic Stairs");
        build.add(EBBlocks.CHERRY_MOSAIC_SLAB, "Cherry Mosaic Slab");
        build.add(EBBlocks.CHERRY_MOSAIC_VERTICAL_STAIRS, "Cherry Mosaic Vertical Stairs");
        build.add(EBBlocks.CRIMSON_MOSAIC, "Crimson Mosaic");
        build.add(EBBlocks.CRIMSON_MOSAIC_STAIRS, "Crimson Mosaic Stairs");
        build.add(EBBlocks.CRIMSON_MOSAIC_SLAB, "Crimson Mosaic Slab");
        build.add(EBBlocks.CRIMSON_MOSAIC_VERTICAL_STAIRS, "Crimson Mosaic Vertical Stairs");
        build.add(EBBlocks.WARPED_MOSAIC, "Warped Mosaic");
        build.add(EBBlocks.WARPED_MOSAIC_STAIRS, "Warped Mosaic Stairs");
        build.add(EBBlocks.WARPED_MOSAIC_SLAB, "Warped Mosaic Slab");
        build.add(EBBlocks.WARPED_MOSAIC_VERTICAL_STAIRS, "Warped Mosaic Vertical Stairs");
        build.add(EBBlocks.BAMBOO_MOSAIC_VERTICAL_STAIRS, "Bamboo Mosaic Vertical Stairs");
        build.add(EBBlocks.COBBLESTONE_BRICKS, "Cobblestone Bricks");
        build.add(EBBlocks.COBBLESTONE_BRICK_STAIRS, "Cobblestone Brick Stairs");
        build.add(EBBlocks.COBBLESTONE_BRICK_SLAB, "Cobblestone Brick Slab");
        build.add(EBBlocks.COBBLESTONE_BRICK_VERTICAL_STAIRS, "Cobblestone Brick Vertical Stairs");
        build.add(EBBlocks.CRACKED_COBBLESTONE_BRICKS, "Cracked Cobblestone Bricks");
        build.add(EBBlocks.MOSSY_COBBLESTONE_BRICKS, "Mossy Cobblestone Bricks");
        build.add(EBBlocks.MOSSY_COBBLESTONE_BRICK_STAIRS, "Mossy Cobblestone Brick Stairs");
        build.add(EBBlocks.MOSSY_COBBLESTONE_BRICK_SLAB, "Mossy Cobblestone Brick Slab");
        build.add(EBBlocks.MOSSY_COBBLESTONE_BRICK_VERTICAL_STAIRS, "Mossy Cobblestone Brick Vertical Stairs");
        build.add(EBBlocks.COBBLED_DEEPSLATE_BRICKS, "Cobbled Deepslate Bricks");
        build.add(EBBlocks.COBBLED_DEEPSLATE_BRICK_STAIRS, "Cobbled Deepslate Brick Stairs");
        build.add(EBBlocks.COBBLED_DEEPSLATE_BRICK_SLAB, "Cobbled Deepslate Brick Slab");
        build.add(EBBlocks.COBBLED_DEEPSLATE_BRICK_VERTICAL_STAIRS, "Cobbled Deepslate Brick Vertical Stairs");
        build.add(EBBlocks.CRACKED_COBBLED_DEEPSLATE_BRICKS, "Cracked Cobbled Deepslate Bricks");
        build.add(EBBlocks.BLACKSTONE_BRICKS, "Blackstone Bricks");
        build.add(EBBlocks.BLACKSTONE_BRICK_STAIRS, "Blackstone Brick Stairs");
        build.add(EBBlocks.BLACKSTONE_BRICK_SLAB, "Blackstone Brick Slab");
        build.add(EBBlocks.BLACKSTONE_BRICK_VERTICAL_STAIRS, "Blackstone Brick Vertical Stairs");
        build.add(EBBlocks.CRACKED_BLACKSTONE_BRICKS, "Cracked Blackstone Bricks");
        build.add(EBBlocks.COBBLESTONE_BRICK_WALL, "Cobblestone Brick Wall");
        build.add(EBBlocks.MOSSY_COBBLESTONE_BRICK_WALL, "Mossy Cobblestone Brick Wall");
        build.add(EBBlocks.COBBLED_DEEPSLATE_BRICK_WALL, "Cobbled Deepslate Brick Wall");
        build.add(EBBlocks.BLACKSTONE_BRICK_WALL, "Blackstone Brick Wall");
        build.add(EBBlocks.LOGO_BLOCK, "Logo Block");
        build.add(EBBlocks.ANCIENT_PLANKS, "Ancient Planks");
        build.add(EBBlocks.ANCIENT_STAIRS, "Ancient Stairs");
        build.add(EBBlocks.ANCIENT_SLAB, "Ancient Slab");
        build.add(EBBlocks.ANCIENT_VERTICAL_STAIRS, "Ancient Vertical Stairs");
        build.add(EBBlocks.ANCIENT_MOSAIC, "Ancient Mosaic");
        build.add(EBBlocks.ANCIENT_MOSAIC_STAIRS, "Ancient Mosaic Stairs");
        build.add(EBBlocks.ANCIENT_MOSAIC_SLAB, "Ancient Mosaic Slab");
        build.add(EBBlocks.ANCIENT_MOSAIC_VERTICAL_STAIRS, "Ancient Mosaic Vertical Stairs");
        build.add(EBBlocks.ANCIENT_BUTTON, "Ancient Button");
        build.add(EBBlocks.ANCIENT_PRESSURE_PLATE, "Ancient Pressure Plate");
        build.add(EBBlocks.ANCIENT_DOOR, "Ancient Door");
        build.add(EBBlocks.ANCIENT_TRAPDOOR, "Ancient Trapdoor");
        build.add(EBBlocks.ANCIENT_LOG, "Ancient Log");
        build.add(EBBlocks.ANCIENT_WOOD, "Ancient Wood");
        build.add(EBBlocks.STRIPPED_ANCIENT_LOG, "Stripped Ancient Log");
        build.add(EBBlocks.STRIPPED_ANCIENT_WOOD, "Stripped Ancient Wood");
        build.add(EBBlocks.ANCIENT_LEAVES, "Ancient Leaves");
        build.add(EBBlocks.ANCIENT_FENCE, "Ancient Fence");
        build.add(EBBlocks.ANCIENT_FENCE_GATE, "Ancient Fence Gate");
        build.add(EBBlocks.ANCIENT_SAPLING, "Ancient Sapling");
        build.add(EBBlocks.POTTED_ANCIENT_SAPLING, "Potted Ancient Sapling");
        build.add(EBBlocks.CHISELED_OAK_PLANKS, "Chiseled Oak Planks");
        build.add(EBBlocks.CHISELED_SPRUCE_PLANKS, "Chiseled Spruce Planks");
        build.add(EBBlocks.CHISELED_BIRCH_PLANKS, "Chiseled Birch Planks");
        build.add(EBBlocks.CHISELED_JUNGLE_PLANKS, "Chiseled Jungle Planks");
        build.add(EBBlocks.CHISELED_ACACIA_PLANKS, "Chiseled Acacia Planks");
        build.add(EBBlocks.CHISELED_DARK_OAK_PLANKS, "Chiseled Dark Oak Planks");
        build.add(EBBlocks.CHISELED_MANGROVE_PLANKS, "Chiseled Mangrove Planks");
        build.add(EBBlocks.CHISELED_BAMBOO_PLANKS, "Chiseled Bamboo Planks");
        build.add(EBBlocks.CHISELED_CRIMSON_PLANKS, "Chiseled Crimson Planks");
        build.add(EBBlocks.CHISELED_WARPED_PLANKS, "Chiseled Warped Planks");
        build.add(EBBlocks.CHISELED_ANCIENT_PLANKS, "Chiseled Ancient Planks");
        build.add(EBBlocks.GLOOM_PLANKS, "Gloom Planks");
        build.add(EBBlocks.GLOOM_STAIRS, "Gloom Stairs");
        build.add(EBBlocks.GLOOM_SLAB, "Gloom Slab");
        build.add(EBBlocks.GLOOM_VERTICAL_STAIRS, "Gloom Vertical Stairs");
        build.add(EBBlocks.GLOOM_MOSAIC, "Gloom Mosaic");
        build.add(EBBlocks.GLOOM_MOSAIC_STAIRS, "Gloom Mosaic Stairs");
        build.add(EBBlocks.GLOOM_MOSAIC_SLAB, "Gloom Mosaic Slab");
        build.add(EBBlocks.GLOOM_MOSAIC_VERTICAL_STAIRS, "Gloom Mosaic Vertical Stairs");
        build.add(EBBlocks.GLOOM_BUTTON, "Gloom Button");
        build.add(EBBlocks.GLOOM_PRESSURE_PLATE, "Gloom Pressure Plate");
        build.add(EBBlocks.GLOOM_DOOR, "Gloom Door");
        build.add(EBBlocks.GLOOM_TRAPDOOR, "Gloom Trapdoor");
        build.add(EBBlocks.GLOOM_LOG, "Gloom Log");
        build.add(EBBlocks.GLOOM_WOOD, "Gloom Wood");
        build.add(EBBlocks.STRIPPED_GLOOM_LOG, "Stripped Gloom Log");
        build.add(EBBlocks.STRIPPED_GLOOM_WOOD, "Stripped Gloom Wood");
        build.add(EBBlocks.GLOOM_FENCE, "Gloom Fence");
        build.add(EBBlocks.GLOOM_FENCE_GATE, "Gloom Fence Gate");
        build.add(EBBlocks.CHISELED_GLOOM_PLANKS, "Chiseled Gloom Planks");
        build.add(EBBlocks.COPPER_BRICKS, "Copper Bricks");
        build.add(EBBlocks.COPPER_BRICK_STAIRS, "Copper Stairs");
        build.add(EBBlocks.COPPER_BRICK_VERTICAL_STAIRS, "Copper Brick Vertical Stairs");
        build.add(EBBlocks.COPPER_BRICK_SLAB, "Copper Slab");
        build.add(EBBlocks.COPPER_PRESSURE_PLATE, "Copper Pressure Plate");
        build.add(EBBlocks.EXPOSED_COPPER_BRICKS, "Exposed Copper Bricks");
        build.add(EBBlocks.EXPOSED_COPPER_BRICK_STAIRS, "Exposed Copper Stairs");
        build.add(EBBlocks.EXPOSED_COPPER_BRICK_VERTICAL_STAIRS, "Exposed Copper Brick Vertical Stairs");
        build.add(EBBlocks.EXPOSED_COPPER_BRICK_SLAB, "Exposed Copper Slab");
        build.add(EBBlocks.EXPOSED_COPPER_PRESSURE_PLATE, "Exposed Copper Pressure Plate");
        build.add(EBBlocks.WEATHERED_COPPER_BRICKS, "Weathered Copper Bricks");
        build.add(EBBlocks.WEATHERED_COPPER_BRICK_STAIRS, "Weathered Copper Stairs");
        build.add(EBBlocks.WEATHERED_COPPER_BRICK_VERTICAL_STAIRS, "Weathered Copper Brick Vertical Stairs");
        build.add(EBBlocks.WEATHERED_COPPER_BRICK_SLAB, "Weathered Copper Slab");
        build.add(EBBlocks.WEATHERED_COPPER_PRESSURE_PLATE, "Weathered Copper Pressure Plate");
        build.add(EBBlocks.OXIDIZED_COPPER_BRICKS, "Oxidized Copper Bricks");
        build.add(EBBlocks.OXIDIZED_COPPER_BRICK_STAIRS, "Oxidized Copper Stairs");
        build.add(EBBlocks.OXIDIZED_COPPER_BRICK_VERTICAL_STAIRS, "Oxidized Copper Brick Vertical Stairs");
        build.add(EBBlocks.OXIDIZED_COPPER_BRICK_SLAB, "Oxidized Copper Slab");
        build.add(EBBlocks.OXIDIZED_COPPER_PRESSURE_PLATE, "Oxidized Copper Pressure Plate");
        build.add(EBBlocks.WAXED_COPPER_BRICKS, "Waxed Copper Bricks");
        build.add(EBBlocks.WAXED_COPPER_BRICK_STAIRS, "Waxed Copper Stairs");
        build.add(EBBlocks.WAXED_COPPER_BRICK_VERTICAL_STAIRS, "Waxed Copper Brick Vertical Stairs");
        build.add(EBBlocks.WAXED_COPPER_BRICK_SLAB, "Waxed Copper Slab");
        build.add(EBBlocks.WAXED_COPPER_PRESSURE_PLATE, "Waxed Copper Pressure Plate");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_BRICKS, "Waxed Exposed Copper Bricks");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_BRICK_STAIRS, "Waxed Exposed Copper Stairs");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_BRICK_VERTICAL_STAIRS, "Waxed Exposed Copper Brick Vertical Stairs");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_BRICK_SLAB, "Waxed Exposed Copper Slab");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_PRESSURE_PLATE, "Waxed Exposed Copper Pressure Plate");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_BRICKS, "Waxed Weathered Copper Bricks");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_BRICK_STAIRS, "Waxed Weathered Copper Stairs");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_BRICK_VERTICAL_STAIRS, "Waxed Weathered Copper Brick Vertical Stairs");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_BRICK_SLAB, "Waxed Weathered Copper Slab");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_PRESSURE_PLATE, "Waxed Weathered Copper Pressure Plate");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_BRICKS, "Waxed Oxidized Copper Bricks");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_BRICK_STAIRS, "Waxed Oxidized Copper Stairs");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_BRICK_VERTICAL_STAIRS, "Waxed Oxidized Copper Brick Vertical Stairs");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_BRICK_SLAB, "Waxed Oxidized Copper Slab");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_PRESSURE_PLATE, "Waxed Oxidized Copper Pressure Plate");
        build.add(EBBlocks.COPPER_BUTTON, "Copper Button");
        build.add(EBBlocks.EXPOSED_COPPER_BUTTON, "Exposed Copper Button");
        build.add(EBBlocks.WEATHERED_COPPER_BUTTON, "Weathered Copper Button");
        build.add(EBBlocks.OXIDIZED_COPPER_BUTTON, "Oxidized Copper Button");
        build.add(EBBlocks.WAXED_COPPER_BUTTON, "Waxed Copper Button");
        build.add(EBBlocks.WAXED_EXPOSED_COPPER_BUTTON, "Waxed Exposed Copper Button");
        build.add(EBBlocks.WAXED_WEATHERED_COPPER_BUTTON, "Waxed Weathered Copper Button");
        build.add(EBBlocks.WAXED_OXIDIZED_COPPER_BUTTON, "Waxed Oxidized Copper Button");
        build.add(EBBlocks.IRON_BRICKS, "Iron Bricks");
        build.add(EBBlocks.IRON_BRICK_STAIRS, "Iron Brick Stairs");
        build.add(EBBlocks.IRON_BRICK_SLAB, "Iron Brick Slab");
        build.add(EBBlocks.IRON_BRICK_VERTICAL_STAIRS, "Iron Brick Vertical Stairs");
        build.add(EBBlocks.GOLD_BRICKS, "Gold Bricks");
        build.add(EBBlocks.GOLD_BRICK_STAIRS, "Gold Brick Stairs");
        build.add(EBBlocks.GOLD_BRICK_SLAB, "Gold Brick Slab");
        build.add(EBBlocks.GOLD_BRICK_VERTICAL_STAIRS, "Gold Brick Vertical Stairs");
        build.add(EBBlocks.LAPIS_BRICKS, "Lapis Bricks");
        build.add(EBBlocks.LAPIS_BRICK_STAIRS, "Lapis Brick Stairs");
        build.add(EBBlocks.LAPIS_BRICK_SLAB, "Lapis Brick Slab");
        build.add(EBBlocks.LAPIS_BRICK_VERTICAL_STAIRS, "Lapis Brick Vertical Stairs");
        build.add(EBBlocks.EMERALD_BRICKS, "Emerald Bricks");
        build.add(EBBlocks.EMERALD_BRICK_STAIRS, "Emerald Brick Stairs");
        build.add(EBBlocks.EMERALD_BRICK_SLAB, "Emerald Brick Slab");
        build.add(EBBlocks.EMERALD_BRICK_VERTICAL_STAIRS, "Emerald Brick Vertical Stairs");
        build.add(EBBlocks.DIAMOND_BRICKS, "Diamond Bricks");
        build.add(EBBlocks.DIAMOND_BRICK_STAIRS, "Diamond Brick Stairs");
        build.add(EBBlocks.DIAMOND_BRICK_SLAB, "Diamond Brick Slab");
        build.add(EBBlocks.DIAMOND_BRICK_VERTICAL_STAIRS, "Diamond Brick Vertical Stairs");
        build.add(EBBlocks.NETHERITE_BRICKS, "Netherite Bricks");
        build.add(EBBlocks.NETHERITE_BRICK_STAIRS, "Netherite Brick Stairs");
        build.add(EBBlocks.NETHERITE_BRICK_SLAB, "Netherite Brick Slab");
        build.add(EBBlocks.NETHERITE_BRICK_VERTICAL_STAIRS, "Netherite Brick Vertical Stairs");
        build.add(EBBlocks.SEA_GLASS, "Sea Glass");
        build.add(EBBlocks.VERDANT_SEA_GLASS, "Verdant Sea Glass");
        build.add(EBBlocks.FUCHSIA_SEA_GLASS, "Fuchsia Sea Glass");
        build.add(EBBlocks.AQUA_SEA_GLASS, "Aqua Sea Glass");
        build.add(EBBlocks.SCARLET_SEA_GLASS, "Scarlet Sea Glass");
        build.add(EBBlocks.ROSE_SEA_GLASS, "Rose Sea Glass");
        build.add(EBBlocks.SEA_GLASS_PANE, "Sea Glass Pane");
        build.add(EBBlocks.VERDANT_SEA_GLASS_PANE, "Verdant Sea Glass Pane");
        build.add(EBBlocks.FUCHSIA_SEA_GLASS_PANE, "Fuchsia Sea Glass Pane");
        build.add(EBBlocks.AQUA_SEA_GLASS_PANE, "Aqua Sea Glass Pane");
        build.add(EBBlocks.SCARLET_SEA_GLASS_PANE, "Scarlet Sea Glass Pane");
        build.add(EBBlocks.ROSE_SEA_GLASS_PANE, "Rose Sea Glass Pane");
        build.add(EBBlocks.BONE_BRICKS, "Bone Bricks");
        build.add(EBBlocks.BONE_BRICK_STAIRS, "Bone Brick Stairs");
        build.add(EBBlocks.BONE_BRICK_SLAB, "Bone Brick Slab");
        build.add(EBBlocks.BONE_BRICK_VERTICAL_STAIRS, "Bone Brick Vertical Stairs");
        build.add(EBBlocks.BONE_BRICK_WALL, "Bone Brick Wall");
        build.add(EBBlocks.SOUL_MAGMA_BLOCK, "Soul Magma Block");
        build.add(EBBlocks.SOUL_SANDSTONE, "Soul Sandstone");
        build.add(EBBlocks.SOUL_SANDSTONE_STAIRS, "Soul Sandstone Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_VERTICAL_STAIRS, "Soul Sandstone Vertical Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_SLAB, "Soul Sandstone Slab");
        build.add(EBBlocks.SOUL_SANDSTONE_WALL, "Soul Sandstone Wall");
        build.add(EBBlocks.CUT_SOUL_SANDSTONE, "Cut Soul Sandstone");
        build.add(EBBlocks.CUT_SOUL_SANDSTONE_SLAB, "Cut Soul Sandstone Slab");
        build.add(EBBlocks.CHISELED_SOUL_SANDSTONE, "Chiseled Soul Sandstone");
        build.add(EBBlocks.SMOOTH_SOUL_SANDSTONE, "Smooth Soul Sandstone");
        build.add(EBBlocks.SMOOTH_SOUL_SANDSTONE_STAIRS, "Smooth Soul Sandstone Stairs");
        build.add(EBBlocks.SMOOTH_SOUL_SANDSTONE_VERTICAL_STAIRS, "Smooth Soul Sandstone Vertical Stairs");
        build.add(EBBlocks.SMOOTH_SOUL_SANDSTONE_SLAB, "Smooth Soul Sandstone Slab");
        build.add(EBBlocks.POLISHED_SANDSTONE, "Polished Sandstone");
        build.add(EBBlocks.POLISHED_SANDSTONE_STAIRS, "Polished Sandstone Stairs");
        build.add(EBBlocks.POLISHED_SANDSTONE_VERTICAL_STAIRS, "Polished Sandstone Vertical Stairs");
        build.add(EBBlocks.POLISHED_SANDSTONE_SLAB, "Polished Sandstone Slab");
        build.add(EBBlocks.POLISHED_SANDSTONE_WALL, "Polished Sandstone Wall");
        build.add(EBBlocks.SANDSTONE_BRICKS, "Sandstone Bricks");
        build.add(EBBlocks.SANDSTONE_BRICK_STAIRS, "Sandstone Brick Stairs");
        build.add(EBBlocks.SANDSTONE_BRICK_VERTICAL_STAIRS, "Sandstone Brick Vertical Stairs");
        build.add(EBBlocks.SANDSTONE_BRICK_SLAB, "Sandstone Brick Slab");
        build.add(EBBlocks.SANDSTONE_BRICK_WALL, "Sandstone Brick Wall");
        build.add(EBBlocks.SANDSTONE_TILES, "Sandstone Tiles");
        build.add(EBBlocks.SANDSTONE_TILE_STAIRS, "Sandstone Tile Stairs");
        build.add(EBBlocks.SANDSTONE_TILE_VERTICAL_STAIRS, "Sandstone Tile Vertical Stairs");
        build.add(EBBlocks.SANDSTONE_TILE_SLAB, "Sandstone Tile Slab");
        build.add(EBBlocks.SANDSTONE_TILE_WALL, "Sandstone Tile Wall");
        build.add(EBBlocks.CHISELED_SANDSTONE_BRICKS, "Chiseled Sandstone Bricks");
        build.add(EBBlocks.DECORATED_SANDSTONE_BRICKS, "Decorated Sandstone Bricks");
        build.add(EBBlocks.ENGRAVED_SANDSTONE_BRICKS, "Engraved Sandstone Bricks");
        build.add(EBBlocks.SANDSTONE_PILLAR, "Sandstone Pillar");
        build.add(EBBlocks.POLISHED_RED_SANDSTONE, "Polished Red Sandstone");
        build.add(EBBlocks.POLISHED_RED_SANDSTONE_STAIRS, "Polished Red Sandstone Stairs");
        build.add(EBBlocks.POLISHED_RED_SANDSTONE_VERTICAL_STAIRS, "Polished Red Sandstone Vertical Stairs");
        build.add(EBBlocks.POLISHED_RED_SANDSTONE_SLAB, "Polished Red Sandstone Slab");
        build.add(EBBlocks.POLISHED_RED_SANDSTONE_WALL, "Polished Red Sandstone Wall");
        build.add(EBBlocks.RED_SANDSTONE_BRICKS, "Red Sandstone Bricks");
        build.add(EBBlocks.RED_SANDSTONE_BRICK_STAIRS, "Red Sandstone Brick Stairs");
        build.add(EBBlocks.RED_SANDSTONE_BRICK_VERTICAL_STAIRS, "Red Sandstone Brick Vertical Stairs");
        build.add(EBBlocks.RED_SANDSTONE_BRICK_SLAB, "Red Sandstone Brick Slab");
        build.add(EBBlocks.RED_SANDSTONE_BRICK_WALL, "Red Sandstone Brick Wall");
        build.add(EBBlocks.RED_SANDSTONE_TILES, "Red Sandstone Tiles");
        build.add(EBBlocks.RED_SANDSTONE_TILE_STAIRS, "Red Sandstone Tile Stairs");
        build.add(EBBlocks.RED_SANDSTONE_TILE_VERTICAL_STAIRS, "Red Sandstone Tile Vertical Stairs");
        build.add(EBBlocks.RED_SANDSTONE_TILE_SLAB, "Red Sandstone Tile Slab");
        build.add(EBBlocks.RED_SANDSTONE_TILE_WALL, "Red Sandstone Tile Wall");
        build.add(EBBlocks.CHISELED_RED_SANDSTONE_BRICKS, "Chiseled Red Sandstone Bricks");
        build.add(EBBlocks.DECORATED_RED_SANDSTONE_BRICKS, "Decorated Red Sandstone Bricks");
        build.add(EBBlocks.ENGRAVED_RED_SANDSTONE_BRICKS, "Engraved Red Sandstone Bricks");
        build.add(EBBlocks.RED_SANDSTONE_PILLAR, "Red Sandstone Pillar");
        build.add(EBBlocks.POLISHED_SOUL_SANDSTONE, "Polished Soul Sandstone");
        build.add(EBBlocks.POLISHED_SOUL_SANDSTONE_STAIRS, "Polished Soul Sandstone Stairs");
        build.add(EBBlocks.POLISHED_SOUL_SANDSTONE_VERTICAL_STAIRS, "Polished Soul Sandstone Vertical Stairs");
        build.add(EBBlocks.POLISHED_SOUL_SANDSTONE_SLAB, "Polished Soul Sandstone Slab");
        build.add(EBBlocks.POLISHED_SOUL_SANDSTONE_WALL, "Polished Soul Sandstone Wall");
        build.add(EBBlocks.SOUL_SANDSTONE_BRICKS, "Soul Sandstone Bricks");
        build.add(EBBlocks.SOUL_SANDSTONE_BRICK_STAIRS, "Soul Sandstone Brick Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_BRICK_VERTICAL_STAIRS, "Soul Sandstone Brick Vertical Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_BRICK_SLAB, "Soul Sandstone Brick Slab");
        build.add(EBBlocks.SOUL_SANDSTONE_BRICK_WALL, "Soul Sandstone Brick Wall");
        build.add(EBBlocks.SOUL_SANDSTONE_TILES, "Soul Sandstone Tiles");
        build.add(EBBlocks.SOUL_SANDSTONE_TILE_STAIRS, "Soul Sandstone Tile Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_TILE_VERTICAL_STAIRS, "Soul Sandstone Tile Vertical Stairs");
        build.add(EBBlocks.SOUL_SANDSTONE_TILE_SLAB, "Soul Sandstone Tile Slab");
        build.add(EBBlocks.SOUL_SANDSTONE_TILE_WALL, "Soul Sandstone Tile Wall");
        build.add(EBBlocks.CHISELED_SOUL_SANDSTONE_BRICKS, "Chiseled Soul Sandstone Bricks");
        build.add(EBBlocks.DECORATED_SOUL_SANDSTONE_BRICKS, "Decorated Soul Sandstone Bricks");
        build.add(EBBlocks.ENGRAVED_SOUL_SANDSTONE_BRICKS, "Engraved Soul Sandstone Bricks");
        build.add(EBBlocks.SOUL_SANDSTONE_PILLAR, "Soul Sandstone Pillar");
        build.add(EBBlocks.SPRUCE_LADDER, "Spruce Ladder");
        build.add(EBBlocks.BIRCH_LADDER, "Birch Ladder");
        build.add(EBBlocks.JUNGLE_LADDER, "Jungle Ladder");
        build.add(EBBlocks.ACACIA_LADDER, "Acacia Ladder");
        build.add(EBBlocks.DARK_OAK_LADDER, "Dark Oak Ladder");
        build.add(EBBlocks.MANGROVE_LADDER, "Mangrove Ladder");
        build.add(EBBlocks.CHERRY_LADDER, "Cherry Ladder");
        build.add(EBBlocks.BAMBOO_LADDER, "Bamboo Ladder");
        build.add(EBBlocks.CRIMSON_LADDER, "Crimson Ladder");
        build.add(EBBlocks.WARPED_LADDER, "Warped Ladder");
        build.add(EBBlocks.ANCIENT_LADDER, "Ancient Ladder");
        build.add(EBBlocks.GLOOM_LADDER, "Gloom Ladder");
        build.add(EBBlocks.SPRUCE_CRAFTING_TABLE, "Spruce Crafting Table");
        build.add(EBBlocks.BIRCH_CRAFTING_TABLE, "Birch Crafting Table");
        build.add(EBBlocks.JUNGLE_CRAFTING_TABLE, "Jungle Crafting Table");
        build.add(EBBlocks.ACACIA_CRAFTING_TABLE, "Acacia Crafting Table");
        build.add(EBBlocks.DARK_OAK_CRAFTING_TABLE, "Dark Oak Crafting Table");
        build.add(EBBlocks.MANGROVE_CRAFTING_TABLE, "Mangrove Crafting Table");
        build.add(EBBlocks.CHERRY_CRAFTING_TABLE, "Cherry Crafting Table");
        build.add(EBBlocks.BAMBOO_CRAFTING_TABLE, "Bamboo Crafting Table");
        build.add(EBBlocks.CRIMSON_CRAFTING_TABLE, "Crimson Crafting Table");
        build.add(EBBlocks.WARPED_CRAFTING_TABLE, "Warped Crafting Table");
        build.add(EBBlocks.ANCIENT_CRAFTING_TABLE, "Ancient Crafting Table");
        build.add(EBBlocks.GLOOM_CRAFTING_TABLE, "Gloom Crafting Table");
        build.add(EBBlocks.WOODEN_MUG, "Wooden Mug");
        build.add(EBBlocks.GLASS_JAR, "Glass Jar");
        build.add(EBBlocks.GLASS_JAR_OF_FIRE, "Glass Jar of Fire");
        build.add(EBBlocks.GLASS_JAR_OF_SOUL_FIRE, "Glass Jar of Soul Fire");
        build.add(EBBlocks.QUARTZ_BRICK_STAIRS, "Quartz Brick Stairs");
        build.add(EBBlocks.QUARTZ_BRICK_SLAB, "Quartz Brick Slab");
        build.add(EBBlocks.QUARTZ_BRICK_VERTICAL_STAIRS, "Quartz Brick Vertical Stairs");
        build.add(EBBlocks.QUARTZ_BRICK_WALL, "Quartz Brick Wall");
        build.add(EBBlocks.CHISELED_CHERRY_PLANKS, "Chiseled Cherry Planks");
        build.add(EBBlocks.TERRACOTTA_TILES, "Terracotta Tiles");
        build.add(EBBlocks.TERRACOTTA_TILE_STAIRS, "Terracotta Tile Stairs");
        build.add(EBBlocks.TERRACOTTA_TILE_SLAB, "Terracotta Tile Slab");
        build.add(EBBlocks.TERRACOTTA_TILE_VERTICAL_STAIRS, "Terracotta Tile Vertical Stairs");
        build.add(EBBlocks.OAK_VERTICAL_STAIRS, "Oak Vertical Stairs");
        build.add(EBBlocks.SPRUCE_VERTICAL_STAIRS, "Spruce Vertical Stairs");
        build.add(EBBlocks.BIRCH_VERTICAL_STAIRS, "Birch Vertical Stairs");
        build.add(EBBlocks.JUNGLE_VERTICAL_STAIRS, "Jungle Vertical Stairs");
        build.add(EBBlocks.ACACIA_VERTICAL_STAIRS, "Acacia Vertical Stairs");
        build.add(EBBlocks.DARK_OAK_VERTICAL_STAIRS, "Dark Oak Vertical Stairs");
        build.add(EBBlocks.MANGROVE_VERTICAL_STAIRS, "Mangrove Vertical Stairs");
        build.add(EBBlocks.CHERRY_VERTICAL_STAIRS, "Cherry Vertical Stairs");
        build.add(EBBlocks.BAMBOO_VERTICAL_STAIRS, "Bamboo Vertical Stairs");
        build.add(EBBlocks.CRIMSON_VERTICAL_STAIRS, "Crimson Vertical Stairs");
        build.add(EBBlocks.WARPED_VERTICAL_STAIRS, "Warped Vertical Stairs");
        build.add(EBBlocks.STONE_VERTICAL_STAIRS, "Stone Vertical Stairs");
        build.add(EBBlocks.STONE_BRICK_VERTICAL_STAIRS, "Stone Brick Vertical Stairs");
        build.add(EBBlocks.COBBLESTONE_VERTICAL_STAIRS, "Cobblestone Vertical Stairs");
        build.add(EBBlocks.MOSSY_STONE_BRICK_VERTICAL_STAIRS, "Mossy Stone Brick Vertical Stairs");
        build.add(EBBlocks.COBBLED_DEEPSLATE_VERTICAL_STAIRS, "Cobbled Deepslate Vertical Stairs");
        build.add(EBBlocks.DEEPSLATE_BRICK_VERTICAL_STAIRS, "Deepslate Brick Vertical Stairs");
        build.add(EBBlocks.DEEPSLATE_TILE_VERTICAL_STAIRS, "Deepslate Tile Vertical Stairs");
        build.add(EBBlocks.POLISHED_DEEPSLATE_VERTICAL_STAIRS, "Polished Deepslate Vertical Stairs");
        build.add(EBBlocks.QUARTZ_VERTICAL_STAIRS, "Quartz Vertical Stairs");
        build.add(EBBlocks.SMOOTH_QUARTZ_VERTICAL_STAIRS, "Smooth Quartz Vertical Stairs");
        build.add(EBBlocks.BRICK_VERTICAL_STAIRS, "Brick Vertical Stairs");
        build.add(EBBlocks.SANDSTONE_VERTICAL_STAIRS, "Sandstone Vertical Stairs");
        build.add(EBBlocks.SMOOTH_SANDSTONE_VERTICAL_STAIRS, "Smooth Sandstone Vertical Stairs");
        build.add(EBBlocks.RED_SANDSTONE_VERTICAL_STAIRS, "Red Sandstone Vertical Stairs");
        build.add(EBBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_STAIRS, "Smooth Red Sandstone Vertical Stairs");
        build.add(EBBlocks.BLACKSTONE_VERTICAL_STAIRS, "Blackstone Vertical Stairs");
        build.add(EBBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_STAIRS, "Polished Blackstone Brick Vertical Stairs");
        build.add(EBBlocks.POLISHED_BLACKSTONE_VERTICAL_STAIRS, "Polished Blackstone Vertical Stairs");
        build.add(EBBlocks.PRISMARINE_VERTICAL_STAIRS, "Prismarine Vertical Stairs");
        build.add(EBBlocks.PRISMARINE_BRICK_VERTICAL_STAIRS, "Prismarine Brick Vertical Stairs");
        build.add(EBBlocks.DARK_PRISMARINE_VERTICAL_STAIRS, "Dark Prismarine Vertical Stairs");
        build.add(EBBlocks.NETHER_BRICK_VERTICAL_STAIRS, "Nether Brick Vertical Stairs");
        build.add(EBBlocks.RED_NETHER_BRICK_VERTICAL_STAIRS, "Red Nether Brick Vertical Stairs");
        build.add(EBBlocks.ANDESITE_VERTICAL_STAIRS, "Andesite Vertical Stairs");
        build.add(EBBlocks.POLISHED_ANDESITE_VERTICAL_STAIRS, "Polished Andesite Vertical Stairs");
        build.add(EBBlocks.GRANITE_VERTICAL_STAIRS, "Granite Vertical Stairs");
        build.add(EBBlocks.POLISHED_GRANITE_VERTICAL_STAIRS, "Polished Granite Vertical Stairs");
        build.add(EBBlocks.DIORITE_VERTICAL_STAIRS, "Diorite Vertical Stairs");
        build.add(EBBlocks.POLISHED_DIORITE_VERTICAL_STAIRS, "Polished Diorite Vertical Stairs");
        build.add(EBBlocks.END_STONE_BRICK_VERTICAL_STAIRS, "End Stone Vertical Stairs");
        build.add(EBBlocks.PURPUR_VERTICAL_STAIRS, "Purpur Vertical Stairs");
        build.add(EBBlocks.MOSSY_COBBLESTONE_VERTICAL_STAIRS, "Mossy Cobblestone Vertical Stairs");
        build.add(EBBlocks.CUT_COPPER_VERTICAL_STAIRS, "Cut Copper Vertical Stairs");
        build.add(EBBlocks.EXPOSED_CUT_COPPER_VERTICAL_STAIRS, "Exposed Cut Copper Vertical Stairs");
        build.add(EBBlocks.WEATHERED_CUT_COPPER_VERTICAL_STAIRS, "Weathered Cut Copper Vertical Stairs");
        build.add(EBBlocks.OXIDIZED_CUT_COPPER_VERTICAL_STAIRS, "Oxidized Cut Copper Vertical Stairs");
        build.add(EBBlocks.WAXED_CUT_COPPER_VERTICAL_STAIRS, "Waxed Cut Copper Vertical Stairs");
        build.add(EBBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_STAIRS, "Waxed Exposed Cut Copper Vertical Stairs");
        build.add(EBBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_STAIRS, "Waxed Weathered Cut Copper Vertical Stairs");
        build.add(EBBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_STAIRS, "Waxed Oxidized Cut Copper Vertical Stairs");
        build.add(EBBlocks.TUFF_VERTICAL_STAIRS, "Tuff Vertical Stairs");
        build.add(EBBlocks.POLISHED_TUFF_VERTICAL_STAIRS, "Polished Tuff Vertical Stairs");
        build.add(EBBlocks.TUFF_BRICK_VERTICAL_STAIRS, "Tuff Brick Vertical Stairs");
        build.add(EBBlocks.GLOOM_SEEDS, "Gloom Seeds");
        build.add(EBBlocks.GRANITE_BRICKS, "Granite Bricks");
        build.add(EBBlocks.GRANITE_BRICK_STAIRS, "Granite Brick Stairs");
        build.add(EBBlocks.GRANITE_BRICK_VERTICAL_STAIRS, "Granite Brick Vertical Stairs");
        build.add(EBBlocks.GRANITE_BRICK_SLAB, "Granite Brick Slab");
        build.add(EBBlocks.GRANITE_BRICK_WALL, "Granite Brick Wall");
        build.add(EBBlocks.DIORITE_BRICKS, "Diorite Bricks");
        build.add(EBBlocks.DIORITE_BRICK_STAIRS, "Diorite Brick Stairs");
        build.add(EBBlocks.DIORITE_BRICK_VERTICAL_STAIRS, "Diorite Brick Vertical Stairs");
        build.add(EBBlocks.DIORITE_BRICK_SLAB, "Diorite Brick Slab");
        build.add(EBBlocks.DIORITE_BRICK_WALL, "Diorite Brick Wall");
        build.add(EBBlocks.ANDESITE_BRICKS, "Andesite Bricks");
        build.add(EBBlocks.ANDESITE_BRICK_STAIRS, "Andesite Brick Stairs");
        build.add(EBBlocks.ANDESITE_BRICK_VERTICAL_STAIRS, "Andesite Brick Vertical Stairs");
        build.add(EBBlocks.ANDESITE_BRICK_SLAB, "Andesite Brick Slab");
        build.add(EBBlocks.ANDESITE_BRICK_WALL, "Andesite Brick Wall");
        build.add(EBBlocks.SMOOTH_BRICKS, "Smooth Bricks");
        build.add(EBBlocks.SMOOTH_BRICK_STAIRS, "Smooth Brick Stairs");
        build.add(EBBlocks.SMOOTH_BRICK_VERTICAL_STAIRS, "Smooth Brick Vertical Stairs");
        build.add(EBBlocks.SMOOTH_BRICK_SLAB, "Smooth Brick Slab");
        build.add(EBBlocks.SMOOTH_BRICK_WALL, "Smooth Brick Wall");
        build.add(EBBlocks.HERRINGBONE_BRICKS, "Herringbone Bricks");
        build.add(EBBlocks.SMOOTH_HERRINGBONE_BRICKS, "Smooth Herringbone Bricks");
        build.add(EBBlocks.CRACKED_BRICKS, "Cracked Bricks");
        build.add(EBBlocks.CRACKED_SMOOTH_BRICKS, "Cracked Smooth Bricks");
        build.add(EBBlocks.REACHING_LANTERN, "Reaching Lantern");

        //ITEMS
        build.add(EBItems.ANCIENT_SIGN, "Ancient Sign");
        build.add(EBItems.ANCIENT_HANGING_SIGN, "Ancient Hanging Sign");
        build.add(EBItems.ANCIENT_FRUIT, "Ancient Fruit");
        build.add(EBItems.GLOOM_SIGN, "Gloom Sign");
        build.add(EBItems.GLOOM_HANGING_SIGN, "Gloom Hanging Sign");

        //SHERDS
        build.add(EBItems.ROYALTY_POTTERY_SHERD, "Royalty Pottery Sherd");
        build.add(EBItems.ANCIENT_POTTERY_SHERD, "Ancient Pottery Sherd");
        build.add(EBItems.BITTER_POTTERY_SHERD, "Bitter Pottery Sherd");
        build.add(EBItems.BOIN_POTTERY_SHERD, "Boin Pottery Sherd");
        build.add(EBItems.BUSTLING_POTTERY_SHERD, "Bustling Pottery Sherd");
        build.add(EBItems.CHECKERED_POTTERY_SHERD, "Checkered Pottery Sherd");
        build.add(EBItems.DECAY_POTTERY_SHERD, "Decay Pottery Sherd");
        build.add(EBItems.DESTRUCTION_POTTERY_SHERD, "Destruction Pottery Sherd");
        build.add(EBItems.FORWARDS_POTTERY_SHERD, "Forwards Pottery Sherd");
        build.add(EBItems.HEXXED_POTTERY_SHERD, "Hexxed Pottery Sherd");
        build.add(EBItems.KITTEH_POTTERY_SHERD, "Kitteh Pottewy Shewd");
        build.add(EBItems.LIFE_POTTERY_SHERD, "Life Pottery Sherd");
        build.add(EBItems.MESMERIZE_POTTERY_SHERD, "Mesmerize Pottery Sherd");
        build.add(EBItems.PORTAL_POTTERY_SHERD, "Portal Pottery Sherd");
        build.add(EBItems.POTTERY_POTTERY_SHERD, "Pottery Pottery Sherd");
        build.add(EBItems.RING_POTTERY_SHERD, "Ring Pottery Sherd");
        build.add(EBItems.SNOUT_POTTERY_SHERD, "Snout Pottery Sherd");
        build.add(EBItems.SPRITE_POTTERY_SHERD, "Sprite Pottery Sherd");
        build.add(EBItems.TWINS_POTTERY_SHERD, "Twins Pottery Sherd");
        build.add(EBItems.WRATHFUL_POTTERY_SHERD, "Wrathful Pottery Sherd");
        build.add(EBItems.IS_THAT_POTTERY_SHERD, "Is That Pottery Sherd");
        build.add(EBItems.KOKOS_BUG_POTTERY_SHERD, "Kokos Bug Pottery Sherd");
        build.add(EBItems.THIEF_POTTERY_SHERD, "Thief Pottery Sherd");

        //TOOLTIPS
        build.add("tooltip.block.interact", "Upon Interaction:");
        build.add("tooltip.block.variant", "Cycles Block Variants:");
        build.add("tooltip.block.interact_sugar", "Interact with Sugar:");
        build.add("tooltip.block.swift", "Increases Movement Speed");
        build.add("tooltip.block.interact_soil", "Interact with Soil:");
        build.add("tooltip.block.fill", "Fills Up Pot");
        build.add("tooltip.block.interact_glow_removals", "Interact with Paper:");
        build.add("tooltip.block.glow_removal", "Removes it's Glow");
        build.add("tooltip.block.when_powered", "When Powered by Redstone:");
        build.add("tooltip.block.soul_magma", "Creates a Lifting Bubble Column");

        //MISC
        build.add("excessive_building.container.kiln", "Kiln");
        build.add("pack.excessive_building.vanilla_retextures", "Vanilla Retextures");

        //ITEM GROUPS
        build.add("itemgroup.excessive_building", "Excessive Building");

        //PAINTING TITLES
        build.add("painting.excessive_building.forgotten_kingdom.title", "Forgotten Kingdom");
        build.add("painting.excessive_building.beacon_of_the_desert.title", "Beacon of the Desert");
        build.add("painting.excessive_building.beacon_of_the_desert_trimmed.title", "Beacon of the Desert (Trimmed)");
        build.add("painting.excessive_building.burrito.title", "Burrito?");
        build.add("painting.excessive_building.courbet_original.title", "Courbet (Original)");
        build.add("painting.excessive_building.crash_landing.title", "Crash Landing");
        build.add("painting.excessive_building.fit_for_a_queen.title", "Fit for a Queen");
        build.add("painting.excessive_building.floors.title", "Floors");
        build.add("painting.excessive_building.horizon.title", "Shine");
        build.add("painting.excessive_building.imminent_detonation.title", "Imminent Detonation");
        build.add("painting.excessive_building.kolos_bug.title", "Kolos Bug");
        build.add("painting.excessive_building.lone_bridge.title", "Lone Bridge");
        build.add("painting.excessive_building.long_trips.title", "Long Trips");
        build.add("painting.excessive_building.paleobotany.title", "Paleobotany");
        build.add("painting.excessive_building.pufferlight.title", "Pufferlight");
        build.add("painting.excessive_building.scourge_bringer.title", "Scourge Bringer");
        build.add("painting.excessive_building.sniffing_in_the_pine_forest.title", "Sniffing in the Pine Forest");
        build.add("painting.excessive_building.stage_original.title", "Stage (Original)");
        build.add("painting.excessive_building.the_end.title", "The End");
        build.add("painting.excessive_building.the_lone_tree.title", "The Lone Tree");
        build.add("painting.excessive_building.thine_holy_peanut.title", "Thine Holy Peanut");
        build.add("painting.excessive_building.why_do_my_eyes_hurt.title", "Bleeding Eclipse");
        build.add("painting.excessive_building.evil_eye.title", "Evil Eye");
        build.add("painting.excessive_building.rebellious.title", "Rebellious");
        build.add("painting.excessive_building.catastrophes_before_the_calamity.title", "Catastrophes Before the Calamity");
        build.add("painting.excessive_building.goodie_malk.title", "Goodie Malk");

        //PAINTING AUTHORS
        build.add("painting.excessive_building.forgotten_kingdom.author", "Yirmiri");
        build.add("painting.excessive_building.beacon_of_the_desert.author", "Brickerman");
        build.add("painting.excessive_building.beacon_of_the_desert_trimmed.author", "Brickerman");
        build.add("painting.excessive_building.burrito.author", "Drisfish");
        build.add("painting.excessive_building.courbet_original.author", "Kristoffer Zetterstrand");
        build.add("painting.excessive_building.crash_landing.author", "BackupCup");
        build.add("painting.excessive_building.fit_for_a_queen.author", "Yirmiri");
        build.add("painting.excessive_building.floors.author", "Brickerman");
        build.add("painting.excessive_building.horizon.author", "HaWii");
        build.add("painting.excessive_building.imminent_detonation.author", "BackupCup");
        build.add("painting.excessive_building.kolos_bug.author", "Kolos");
        build.add("painting.excessive_building.lone_bridge.author", "Nebula");
        build.add("painting.excessive_building.long_trips.author", "SmillyScarfs");
        build.add("painting.excessive_building.paleobotany.author", "Hecco");
        build.add("painting.excessive_building.pufferlight.author", "Pepagg");
        build.add("painting.excessive_building.scourge_bringer.author", "BackupCup");
        build.add("painting.excessive_building.sniffing_in_the_pine_forest.author", "Brickerman");
        build.add("painting.excessive_building.stage_original.author", "Kristoffer Zetterstrand");
        build.add("painting.excessive_building.the_end.author", "BackupCup");
        build.add("painting.excessive_building.the_lone_tree.author", "SuperMightByte");
        build.add("painting.excessive_building.thine_holy_peanut.author", "YesMan2");
        build.add("painting.excessive_building.why_do_my_eyes_hurt.author", "BackupCup");
        build.add("painting.excessive_building.evil_eye.author", "Yirmiri");
        build.add("painting.excessive_building.rebellious.author", "Rebel (the dog)");
        build.add("painting.excessive_building.catastrophes_before_the_calamity.author", "BackupCup");
        build.add("painting.excessive_building.goodie_malk.author", "Goodie");

        //EFFECTS
        build.add("effect.excessive_building.reaching", "Reaching");
        build.add("effect.excessive_building.reaching.description", "Increases the interaction reach of the user, this does not affect attack reach.");

        build.add("item.minecraft.potion.effect.reaching_potion", "Potion of Reaching");
        build.add("item.minecraft.splash_potion.effect.reaching_potion", "Splash Potion of Reaching");
        build.add("item.minecraft.lingering_potion.effect.reaching_potion", "Lingering Potion of Reaching");
        build.add("item.minecraft.tipped_arrow.effect.reaching_potion", "Arrow of Reaching");

        build.add("item.minecraft.potion.effect.long_reaching_potion", "Potion of Reaching");
        build.add("item.minecraft.splash_potion.effect.long_reaching_potion", "Splash Potion of Reaching");
        build.add("item.minecraft.lingering_potion.effect.long_reaching_potion", "Lingering Potion of Reaching");
        build.add("item.minecraft.tipped_arrow.effect.long_reaching_potion", "Arrow of Reaching");

        build.add("item.minecraft.potion.effect.strong_reaching_potion", "Potion of Reaching");
        build.add("item.minecraft.splash_potion.effect.strong_reaching_potion", "Splash Potion of Reaching");
        build.add("item.minecraft.lingering_potion.effect.strong_reaching_potion", "Lingering Potion of Reaching");
        build.add("item.minecraft.tipped_arrow.effect.strong_reaching_potion", "Arrow of Reaching");

        build.add("effect.excessive_building.shortening", "Shortening");
        build.add("effect.excessive_building.shortening.description", "Decreases the interaction reach of the user, this does not affect attack reach.");

        build.add("item.minecraft.potion.effect.shortening_potion", "Potion of Shortening");
        build.add("item.minecraft.splash_potion.effect.shortening_potion", "Splash Potion of Shortening");
        build.add("item.minecraft.lingering_potion.effect.shortening_potion", "Lingering Potion of Shortening");
        build.add("item.minecraft.tipped_arrow.effect.shortening_potion", "Arrow of Shortening");

        build.add("item.minecraft.potion.effect.long_shortening_potion", "Potion of Shortening");
        build.add("item.minecraft.splash_potion.effect.long_shortening_potion", "Splash Potion of Shortening");
        build.add("item.minecraft.lingering_potion.effect.long_shortening_potion", "Lingering Potion of Shortening");
        build.add("item.minecraft.tipped_arrow.effect.long_shortening_potion", "Arrow of Shortening");

        build.add("item.minecraft.potion.effect.strong_shortening_potion", "Potion of Shortening");
        build.add("item.minecraft.splash_potion.effect.strong_shortening_potion", "Splash Potion of Shortening");
        build.add("item.minecraft.lingering_potion.effect.strong_shortening_potion", "Lingering Potion of Shortening");
        build.add("item.minecraft.tipped_arrow.effect.strong_shortening_potion", "Arrow of Shortening");

        //YAPPING TOOLTIPS [COMPAT]
        //TODO: ADD
    }
}
